
default: &default
  adapter: mysql2
  encoding: utf8
  username: root

development:
  <<: *default
  database: tweetstream_development

test:
  <<: *default
  database: tweetstream_test

production:
  <<: *default
  database: tweetstream_production
